openapi: 3.0.3

info:
  title: tomeit API
  description: tomeit の REST API の仕様書である.
  version: 0.3.0

servers:
  - url: http://localhost:8080/v0
    description: ローカルの開発用 API サーバ

tags:
  - name: tasks
    description: タスク関連 API
  - name: pomodoros
    description: ポモドーロ関連 API

paths:
  /tasks:
    post:
      tags:
        - tasks
      summary: タスク作成 API
      description: タスクを作成する
      parameters:
        - $ref: "#/components/parameters/idToken"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  example: タスク1
                expectedPomodoroNum:
                  type: integer
                  example: 4
                dueOn:
                  type: string
                  example: "2021-12-31T00:00:00Z"
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/AuthenticationError"
    get:
      tags:
        - tasks
      summary: タスク一覧取得 API
      description: |
        タスクを一覧で取得する

        作成順で最大30件まで取得する.
      parameters:
        - $ref: "#/components/parameters/idToken"
        - name: isCompleted
          description: タスクが完了済みかどうかで絞り込みを行う. 省略可能.
          in: "query"
          schema:
            type: string
            example: "false"
        - name: completedOn
          description: タスクを完了した日付で絞り込む. 省略可能.
          in: "query"
          schema:
            type: string
            example: "2021-01-01T00:00:00Z"
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tasks"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/AuthenticationError"
  /tasks/{taskId}:
    patch:
      summary: タスク一部更新 API
      tags:
        - tasks
      description: |
        タスクの一部情報を更新する

        status の値のみ変更できる.
      parameters:
        - $ref: "#/components/parameters/idToken"
        - $ref: "#/components/parameters/taskId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                isCompleted:
                  type: string
                  example: "false"
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/AuthenticationError"
        "403":
          $ref: "#/components/responses/AuthorizationError"
    delete:
      summary: タスク削除 API
      tags:
        - tasks
      description: タスクを削除する
      parameters:
        - $ref: "#/components/parameters/idToken"
        - $ref: "#/components/parameters/taskId"
      responses:
        "204":
          description: 成功
        "401":
          $ref: "#/components/responses/AuthenticationError"
        "403":
          $ref: "#/components/responses/AuthorizationError"
  /pomodoros:
    post:
      summary: ポモドーロ記録 API
      tags:
        - pomodoros
      description: |
        実行したポモドーロを記録する
      parameters:
        - $ref: "#/components/parameters/idToken"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - taskId
              properties:
                taskId:
                  type: integer
                  example: 1
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pomodoro"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/AuthenticationError"
    get:
      summary: ポモドーロ記録一覧取得 API
      tags:
        - pomodoros
      description: |
        ポモドーロ記録を一覧で取得する

        作成順で最大30件まで取得する.
      parameters:
        - $ref: "#/components/parameters/idToken"
        - name: completedOn
          in: "query"
          description: 完了した日付で絞り込む
          schema:
            type: string
            example: "2021-01-01T00:00:00Z"
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pomodoros"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/AuthenticationError"
  /pomodoros/{pomodoroId}:
    delete:
      summary: ポモドーロ記録削除 API
      tags:
        - pomodoros
      description: ポモドーロ記録を削除する
      parameters:
        - $ref: "#/components/parameters/idToken"
        - $ref: "#/components/parameters/pomodoroId"
      responses:
        "204":
          description: 成功
        "401":
          $ref: "#/components/responses/AuthenticationError"
        "403":
          $ref: "#/components/responses/AuthorizationError"
  /pomodoros/rest-count:
    get:
      summary: 次の長い休憩までのカウント取得 API
      tags:
        - pomodoros
      description: |
        次の長い休憩までのカウントを取得する
      parameters:
        - $ref: "#/components/parameters/idToken"
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  restCount:
                    type: integer
                    example: 3
        "401":
          $ref: "#/components/responses/AuthenticationError"

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - notes
        - expectedPomodoroNum
        - actualPomodoroNum
        - dueOn
        - isCompleted
        - completedOn
        - createdAt
        - updatedAt
      properties:
        id:
          description: タスク ID
          type: integer
          minimum: 1
          example: 1
        title:
          description: タスクのタイトル
          type: string
          example: タスク1
        notes:
          description: タスクについてのメモ
          type: string
          example: タスク1のメモ
        expectedPomodoroNum:
          description: 予測ポモドーロ数
          type: integer
          example: 4
        actualPomodoroNum:
          description: 完了したポモドーロ数
          type: integer
          example: 2
        dueOn:
          description: |
            タスクの期限日付

            オプション. 存在しない場合は ""（空の文字列）を返す.
          type: string
          example: "2021-01-01T00:00:00Z"
        isCompleted:
          description: タスクを完了したかどうか
          type: boolean
        completedOn:
          description: |
            タスクを完了した日付

            タスクが完了済みでない場合は ""（空の文字列）を返す.
          type: string
          example: "2021-01-01T00:00:00Z"
        createdAt:
          description: タスクを作成した時刻
          type: string
          example: "2021-01-01T00:00:00Z"
        updatedAt:
          description: タスクを更新した時刻
          type: string
          example: "2021-01-01T00:00:00Z"
    Tasks:
      type: object
      required:
        - tasks
      properties:
        tasks:
          description: タスク一覧
          type: array
          items:
            $ref: "#/components/schemas/Task"
    Pomodoro:
      type: object
      required:
        - id
        - task
        - completedAt
      properties:
        id:
          description: ポモドーロ記録 ID
          type: integer
          minimum: 1
          example: 1
        task:
          $ref: "#/components/schemas/Task"
        completedAt:
          description: ポモドーロを完了した時刻
          type: string
          example: "2021-01-01T00:00:00Z"
    Pomodoros:
      type: object
      required:
        - pomodoros
      properties:
        pomodoros:
          description: ポモドーロ記録一覧
          type: array
          items:
            $ref: "#/components/schemas/Pomodoro"
    Error:
      type: object
      required:
        - status
        - error
      properties:
        status:
          description: レスポンスの説明
          type: string
          example: some response message
        error:
          description: エラーの説明
          type: string
          example: some error message
  responses:
    BadRequestError:
      description: リクエストが間違っている
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    AuthenticationError:
      description: ユーザを認証できない
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    AuthorizationError:
      description: リソースへのアクセス権限がない
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalServerError:
      description: サーバ側で不明なエラーが発生した
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  parameters:
    idToken:
      name: Authorization
      in: header
      description: ユーザ識別用の Firebase ID トークン
      required: true
      schema:
        type: string
    taskId:
      name: taskId
      in: path
      description: 任意のタスク ID
      required: true
      schema:
        type: integer
        minimum: 1
    pomodoroId:
      name: pomodoroId
      in: path
      description: 任意のタスク ID
      required: true
      schema:
        type: integer
        minimum: 1
