openapi: 3.0.3

info:
  title: tomeit API 仕様書
  description: tomeit の REST API の仕様書である.
  version: 0.2.0

servers:
  - url: http://localhost:8080/v0
    description: ローカルの開発用 API サーバ

tags:
  - name: tasks
    description: タスク関連 API
  - name: pomodoros
    description: ポモドーロ関連 API

paths:
  /tasks:
    post:
      tags:
        - tasks
      summary: タスク作成 API
      description: タスクを作成する
      parameters:
        - $ref: "#/components/parameters/id-token"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  example: タスク1
                expectedPomodoroNumber:
                  type: integer
                  example: 4
                dueOn:
                  type: string
                  example: "2021-12-31T00:00:00Z"
      responses:
        "201":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/AuthenticationError"
        "405":
          $ref: "#/components/responses/MethodError"
    get:
      tags:
        - tasks
      summary: タスク一覧取得 API
      description: |
        タスクを一覧で取得する

        作成順で最大30件まで取得する.
        クエリパラメータの is-completed, completed-at で絞り込みが可能である.
        どちらのクエリパラメータも省略可能であり, 両方とも指定しても良い.
      parameters:
        - $ref: "#/components/parameters/id-token"
        - name: is-completed
          in: "query"
          schema:
            type: boolean
        - name: completed-at
          in: "query"
          schema:
            type: string
            example: "2021-01-01T00:00:00Z"
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: object
                required:
                  - tasks
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: "#/components/schemas/Task"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/AuthenticationError"
        "405":
          $ref: "#/components/responses/MethodError"
  /tasks/{task-id}:
    patch:
      summary: タスク一部更新 API
      tags:
        - tasks
      description: |
        タスクの一部情報を更新する

        task-id で更新する一意のタスクを特定する.
        現在は isCompleted の値のみ変更できる.
      parameters:
        - $ref: "#/components/parameters/id-token"
        - $ref: "#/components/parameters/task-id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                isCompleted:
                  type: boolean
                  example: true
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/AuthenticationError"
        "403":
          $ref: "#/components/responses/AuthorizationError"
        "405":
          $ref: "#/components/responses/MethodError"
  /pomodoros:
    post:
      summary: ポモドーロ記録 API
      tags:
        - pomodoros
      description: |
        実行したポモドーロを記録する
      parameters:
        - $ref: "#/components/parameters/id-token"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                taskID:
                  type: integer
                  example: 1
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pomodoro"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/AuthorizationError"
        "405":
          $ref: "#/components/responses/MethodError"
    get:
      summary: ポモドーロ記録一覧取得 API
      tags:
        - pomodoros
      description: |
        ポモドーロ記録を一覧で取得する

        作成順で最大30件まで取得する.
      parameters:
        - $ref: "#/components/parameters/id-token"
        - name: completed-at
          in: "query"
          description: completedAt でポモドーロ記録を絞り込む
          schema:
            description: ポモドーロを実行した時間
            type: string
            example: "2021-01-01T00:00:00Z"
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: object
                required:
                  - pomodoros
                properties:
                  pomodoros:
                    type: array
                    items:
                      $ref: "#/components/schemas/Pomodoro"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/AuthenticationError"
        "405":
          $ref: "#/components/responses/MethodError"
  /pomodoros/next-rest-count:
    get:
      summary: 次の15分休憩までのカウント取得 API
      tags:
        - pomodoros
      description: |
        次の15分休憩までの実行する必要のあるポモドーロの数を取得する
      parameters:
        - $ref: "#/components/parameters/id-token"
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  nextRestCount:
                    type: integer
                    example: 3
        "401":
          $ref: "#/components/responses/AuthenticationError"
        "405":
          $ref: "#/components/responses/MethodError"

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - expectedPomodoroNumber
        - actualPomodoroNumber
        - dueOn
        - isCompleted
        - completedAt
        - createdAt
        - updatedAt
      properties:
        id:
          description: タスク ID
          type: integer
          minimum: 1
          example: 1
        title:
          description: タスクタイトル
          type: string
          example: "タスク1"
        expectedPomodoroNumber:
          description: 予測ポモドーロ数
          type: integer
          example: 4
        actualPomodoroNumber:
          description: 実際のポモドーロ数
          type: integer
          example: 2
        dueOn:
          description: タスクの期限
          type: string
          example: "2021-01-01T00:00:00Z"
        isCompleted:
          description: タスクを完了したかどうか
          type: boolean
        completedAt:
          description: |
            タスクを完了した時刻

            タスクが完了済みでない場合は 0001-01-01T00:00:00Z を返す.
          type: string
          example: "2021-01-01T00:00:00Z"
        createdAt:
          description: タスクを作成した時刻
          type: string
          example: "2021-01-01T00:00:00Z"
        updatedAt:
          description: タスクを更新した時刻
          type: string
          example: "2021-01-01T00:00:00Z"
    Pomodoro:
      type: object
      required:
        - id
        - task
        - completedAt
      properties:
        id:
          description: ポモドーロ記録 ID
          type: integer
          minimum: 1
          example: 1
        task:
          $ref: "#/components/schemas/Task"
        completedAt:
          description: ポモドーロを完了した時刻
          type: string
          example: "2021-01-01T00:00:00Z"
    Error:
      type: object
      required:
        - status
        - error
      properties:
        status:
          description: レスポンスの説明
          type: string
          example: some response message
        error:
          description: エラーの説明
          type: string
          example: some error message
  responses:
    BadRequestError:
      description: リクエストが間違っている
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    AuthenticationError:
      description: ユーザが認証できない
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    AuthorizationError:
      description: リソースへのアクセス権限がない
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    MethodError:
      description: リクエストメソッドが間違っている
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalServerError:
      description: サーバ側で不明なエラーが発生した
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  parameters:
    id-token:
      name: Authorization
      in: header
      description: ユーザ識別用の Firebase ID トークン
      required: true
      schema:
        type: string
    task-id:
      name: task-id
      in: path
      description: タスクの一意の番号
      required: true
      schema:
        type: integer
        minimum: 1
