name: check-go-code
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.1'
      - run: go install honnef.co/go/tools/cmd/staticcheck@2021.1.1
      - run: go mod tidy
      - run: go vet ./...
      - run: staticcheck ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.1'
      - run: go mod tidy
      - run: docker --version
      - run: docker compose up -d db-test
      - run: go test
      - run: docker compose down
