name: check-go-code
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.1'
      - run: go install honnef.co/go/tools/cmd/staticcheck@2021.1.1
      - run: go mod tidy
      - run: go vet ./...
      - run: staticcheck ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.1'
      - run: go mod tidy
      - run: docker-compose up -d db-test
        env:
          PORT: mock
          DSN: mock
          GOOGLE_CREDENTIALS_JSON: mock
          ALLOW_ORIGINS: mock
          MYSQL_ROOT_PASSWORD: mock
          MYSQL_DATABASE: mock
          MYSQL_USER: mock
          MYSQL_PASSWORD: mock
      - run: go test
      - run: docker-compose down
