name: check-go-code
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.1'
      - run: go mod tidy
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: go vet ./...
